
theme: jekyll-theme-dinky

# Name of website
title: Pavel Chernov

# Your name to show in the footer
name: Pavel B. Chernov
author: Pavel B. Chernov
logo: /assets/avatar.png
description: This blog is for sharing notes on my journey in machine learning.

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "/aboutme.md"
  Education: "/education.md"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://diovisgood.github.io"
  
  
# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "pavel.b.chernov@gmail.com"
  facebook: pavel.b.chernov
  github: diovisgood
#  twitter: daattali
#  patreon: DeanAttali
#  youtube: c/daattali
  medium: pavelchernov
#  reddit: yourname
  linkedin: pavel-b-chernov
#  xing: yourname
  stackoverflow: "420951/pavel-chernov"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
  telegram: diover
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar

# If you want to show a link to an RSS in the footer, add the site description here.
# If you don't want to show an RSS link, remove the following line.
rss-description: This blog is for sharing notes on my journey in machine learning.

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false


# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "DiovIsGood.github.io"

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# The keywords to associate with your website, for SEO purposes
keywords: "machine learning,ML,deep learning,DL,genetic algorithms,neural networks,NN,reinforcement learning,RL"

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Moscow"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-sitemap
